### ISSUE TITLE
Accessing BundleHeaders in FindHook causes StackOverflow Exception

### ISSUE THREAD

**Issue by tomsontom** [eclipse-efx/efxclipse-rt#300]
have a (Bundle) FindHook, that checks some Headers of the Bundle, simplified code to reproduce:

```java
@Override
public void find(BundleContext context, Collection<Bundle> bundles) {

	for(Iterator<Bundle> iterator = bundles.iterator(); iterator.hasNext();) {
		Bundle bundle = (Bundle)iterator.next();
		try {
			bundle.getHeaders();
			
		} catch(Throwable e) {
			e.printStackTrace();
		}
	}
}
```

this triggers a StackOverflow

```
java.lang.StackOverflowError
	at sun.nio.cs.UTF_8.updatePositions(UTF_8.java:77)
	at sun.nio.cs.UTF_8.access$200(UTF_8.java:57)
	at sun.nio.cs.UTF_8$Encoder.encodeArrayLoop(UTF_8.java:636)
	at sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:691)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:579)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:271)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
	at java.io.PrintStream.write(PrintStream.java:526)
	at java.io.PrintStream.print(PrintStream.java:669)
	at java.io.PrintStream.println(PrintStream.java:806)
	at org.eclipse.fx.osgi.fxloader.FXClassLoader.createClassLoader(FXClassLoader.java:90)
	at org.eclipse.osgi.internal.loader.BundleLoader.createClassLoaderPrivledged(BundleLoader.java:286)
	at org.eclipse.osgi.internal.loader.BundleLoader.getModuleClassLoader(BundleLoader.java:231)
	at org.eclipse.osgi.internal.loader.BundleLoader.findEntries(BundleLoader.java:796)
	at org.eclipse.osgi.container.ModuleWiring.findEntries(ModuleWiring.java:289)
	at org.eclipse.osgi.storage.ManifestLocalization.findResource(ManifestLocalization.java:200)
	at org.eclipse.osgi.storage.ManifestLocalization.lookupResourceBundle(ManifestLocalization.java:131)
	at org.eclipse.osgi.storage.ManifestLocalization.getResourceBundle(ManifestLocalization.java:102)
	at org.eclipse.osgi.storage.ManifestLocalization.getHeaders(ManifestLocalization.java:63)
	at org.eclipse.osgi.storage.BundleInfo$Generation.getHeaders(BundleInfo.java:124)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.privGetHeaders(EquinoxBundle.java:462)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getHeaders(EquinoxBundle.java:457)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getHeaders(EquinoxBundle.java:451)
	at < this is my FindHook >.find(GerstelBundleFilter.java:56)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.call(BundleContextImpl.java:227)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHookPrivileged(ServiceRegistry.java:1280)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHooksPrivileged(ServiceRegistry.java:1263)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.notifyFindHooksPriviledged(BundleContextImpl.java:224)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.notifyFindHooks(BundleContextImpl.java:209)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getBundles(BundleContextImpl.java:197)
	at org.eclipse.fx.osgi.fxloader.FXClassLoader.getSWTClassloader(FXClassLoader.java:101)
	at org.eclipse.fx.osgi.fxloader.FXClassLoader.getFXClassloader(FXClassLoader.java:73)
	at org.eclipse.fx.osgi.fxloader.FXClassLoader.createClassLoader(FXClassLoader.java:91)
	at org.eclipse.osgi.internal.loader.BundleLoader.createClassLoaderPrivledged(BundleLoader.java:286)
	at org.eclipse.osgi.internal.loader.BundleLoader.getModuleClassLoader(BundleLoader.java:231)
	at org.eclipse.osgi.internal.loader.BundleLoader.findEntries(BundleLoader.java:796)
	at org.eclipse.osgi.container.ModuleWiring.findEntries(ModuleWiring.java:289)
	at org.eclipse.osgi.storage.ManifestLocalization.findResource(ManifestLocalization.java:200)
	at org.eclipse.osgi.storage.ManifestLocalization.lookupResourceBundle(ManifestLocalization.java:131)
	at org.eclipse.osgi.storage.ManifestLocalization.getResourceBundle(ManifestLocalization.java:102)
	at org.eclipse.osgi.storage.ManifestLocalization.getHeaders(ManifestLocalization.java:63)
	at org.eclipse.osgi.storage.BundleInfo$Generation.getHeaders(BundleInfo.java:124)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.privGetHeaders(EquinoxBundle.java:462)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getHeaders(EquinoxBundle.java:457)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getHeaders(EquinoxBundle.java:451)
	at < this is my FindHook >.find(GerstelBundleFilter.java:56)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.call(BundleContextImpl.java:227)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHookPrivileged(ServiceRegistry.java:1280)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHooksPrivileged(ServiceRegistry.java:1263)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.notifyFindHooksPriviledged(BundleContextImpl.java:224)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.notifyFindHooks(BundleContextImpl.java:209)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getBundles(BundleContextImpl.java:197)
	at org.eclipse.fx.osgi.fxloader.FXClassLoader.getSWTClassloader(FXClassLoader.java:101)
	at org.eclipse.fx.osgi.fxloader.FXClassLoader.getFXClassloader(FXClassLoader.java:73)
	at org.eclipse.fx.osgi.fxloader.FXClassLoader.createClassLoader(FXClassLoader.java:91)
	at org.eclipse.osgi.internal.loader.BundleLoader.createClassLoaderPrivledged(BundleLoader.java:286)
	at org.eclipse.osgi.internal.loader.BundleLoader.getModuleClassLoader(BundleLoader.java:231)
	at org.eclipse.osgi.internal.loader.BundleLoader.findEntries(BundleLoader.java:796)
	at org.eclipse.osgi.container.ModuleWiring.findEntries(ModuleWiring.java:289)
	at org.eclipse.osgi.storage.ManifestLocalization.findResource(ManifestLocalization.java:200)
	at org.eclipse.osgi.storage.ManifestLocalization.lookupResourceBundle(ManifestLocalization.java:131)
	at org.eclipse.osgi.storage.ManifestLocalization.getResourceBundle(ManifestLocalization.java:102)
	at org.eclipse.osgi.storage.ManifestLocalization.getHeaders(ManifestLocalization.java:63)
	at org.eclipse.osgi.storage.BundleInfo$Generation.getHeaders(BundleInfo.java:124)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.privGetHeaders(EquinoxBundle.java:462)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getHeaders(EquinoxBundle.java:457)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getHeaders(EquinoxBundle.java:451)
	[... and so on ...]
```

It seems to have something to do with the ManifestLocalization but I don't understand why reading the Manifest-Headers (and localization) should trigger any code execution, since all this stuff should be static bundle resource.

**Comment by tomsontom** [comment]
Moved from https://bugs.eclipse.org/bugs/show_bug.cgi?id=544163

**Comment by tomsontom** [comment]
So we need to avoid calling `BundleContext#getBundles()` which we currently use in 3 places:
* finding the SWT-Bundle
* finding Bundles who change the ModuleLayer configuration
* finding Bundles who load the JPMS-Modules will spin the extra layer from

**Comment by laeubi** [comment]
About the first case: FXClassLoader seem to eagerly fetch the SWT-Classloader.
Might it be possible to only fetch it on the first request for loading an real SWT-class?
