### ISSUE TITLE
Unable to make final void javafx.scene.Node.reapplyCSS() accessible

### ISSUE THREAD

**Issue by SimonScholz** [eclipse-efx/efxclipse-rt#332]
Hi,

I am using the javafx-sdk-11.0.2 and running the application works for me, but I open a dialog I get the following exception:

```
17:43:27.989	ERROR	o.e.fx.ui.controls.JavaFXCompatUtil 	[  95]	Unable to call Node#reapplyCSS()	java.lang.reflect.InaccessibleObjectException: Unable to make final void javafx.scene.Node.reapplyCSS() accessible: module javafx.graphics does not "opens javafx.scene" to unnamed module @26cc7cc7
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at org.eclipse.fx.ui.controls.JavaFXCompatUtil.reapplyCSS(JavaFXCompatUtil.java:127)
	at org.eclipse.fx.ui.controls.dialog.Dialog.lambda$2(Dialog.java:116)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

Is there any chance to avoid this java.lang.reflect.InaccessibleObjectException exception?

The error is raised when https://github.com/eclipse-efx/efxclipse-rt/blob/cfdb23a65333a59524db1b1a198a3344308418fe/modules/ui/org.eclipse.fx.ui.controls/src/main/java/org/eclipse/fx/ui/controls/JavaFXCompatUtil.java#L127 is called.

**Comment by tomsontom** [comment]
I don't fully understand the reason why this exception happens. `javafx.scene` is an exported package so there does have to be an opens clause for it. 

I need to see if this can be reproduced in simple none-osgi application.

**Comment by tomsontom** [comment]
Ok one should read the doc from setAccessible who clear states that one can only make a private-method accessible if the package is exported to the calling module
