### ISSUE TITLE
AbstractE4Application in 3.5.0 fails on Eclipse 2019-03

### ISSUE THREAD

**Issue by eliasvasylenko** [eclipse-efx/efxclipse-rt#365]
`AbstractE4Application` does not work in Eclipse 2019-03 or later, because it calls `ReflectionContributionFactory(IExtensionRegistry)` which has been removed https://git.eclipse.org/c/platform/eclipse.platform.ui.git/commit/?id=2b40ea887ab18f51de501af05f843fc47595414d

Furthermore the broken requirement is not caught by the framework because the bundle requirement on `org.eclipse.e4.ui.workbench` is versionless, which seems a little risky considering it's a dependency on internal API, so we only get a runtime error:

```
java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.NoSuchMethodError: org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.<init>(Lorg/eclipse/core/runtime/IExtensionRegistry;)V
	at org.eclipse.fx.ui.workbench.base.AbstractE4Application.createApplicationContext(AbstractE4Application.java:453)
	at org.eclipse.fx.ui.workbench.fx.E4Application.initE4Workbench(E4Application.java:342)
	at org.eclipse.fx.ui.workbench.fx.E4Application$1.run(E4Application.java:215)
	at org.eclipse.fx.ui.workbench.fx.E4Application.jfxStart(E4Application.java:253)
	at org.eclipse.fx.ui.workbench.fx.DefaultJFXApp.start(DefaultJFXApp.java:60)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more
```

As an aside, is it documented anywhere which versions of Eclipse are supported as targets? I can't seem to find this information. I assumed that since the e(fx)clipse *tooling* can be deployed into a 2019-03+ IDE then the e(fx)clipse *runtime* would also support being deployed against a 2019-03 based RCP target, but this does not appear to be the case.

**Comment by tomsontom** [comment]
I don't think it is documented what versions we support but I guess most people use the target provided by us who is still on an older version - 

https://github.com/eclipse-efx/efxclipse-rt/blob/3.x/releng/org.eclipse.fx.target.ext.releng/pom.xml - we can pump the version for the 3.7.0 release but we are often very conservative because in the past the platform broke stuff which we then had to fix.

**Comment by martinbluehweis** [comment]
#389 lifts the platform to 2019-12 and contains a fix for that
