### ISSUE TITLE
IllegalAccessError on simple application

### ISSUE THREAD

**Issue by MarceloRuiz** [eclipse-efx/efxclipse-rt#405]
Following instructions at: [https://tomsondev.bestsolution.at/2020/01/28/setting-up-efxclipse-rcp-development-for-java11-and-pde/](url), I could an empty application, but I got an IllegalAccessError Exception:

```
May 10, 2020 11:06:39 PM org.eclipse.fx.ui.workbench.fx.DefaultJFXApp setProductApplicationName
SEVERE: Failed to set application name
java.lang.IllegalAccessError: Class org/eclipse/fx/ui/workbench/fx/DefaultJFXApp(unnamed module 0x0000000706255948) can not access class com/sun/glass/ui/Application(module javafx.graphics) because module module javafx.graphics does not export package com/sun/glass/ui to module unnamed module 0x0000000706255948
	at org.eclipse.fx.ui.workbench.fx.DefaultJFXApp.setProductApplicationName(DefaultJFXApp.java:82)
	at org.eclipse.fx.ui.workbench.fx.DefaultJFXApp.<init>(DefaultJFXApp.java:54)
	at org.eclipse.fx.ui.workbench.fx.DefaultJFXApp.<init>(DefaultJFXApp.java:39)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:802)
	at com.sun.javafx.application.LauncherImpl$$Lambda$181/0000000000000000.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl$$Lambda$183/0000000000000000.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at com.sun.javafx.application.PlatformImpl$$Lambda$185/0000000000000000.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.javafx.application.PlatformImpl$$Lambda$184/0000000000000000.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$173/0000000000000000.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by initialflame** [comment]
I have the same error and looking for help...

**Comment by tomsontom** [comment]
I guess we need to add some more trace information to see why the AddOpens/AddExports of the modules are not honored in that case while they are in others.
