### ISSUE TITLE
FXClassloader is not reliable (randomly NoClassDefFoundError)

### ISSUE THREAD

**Issue by qtran** [eclipse-efx/efxclipse-rt#413]
Hi,
ich have an e4 Application with over 100 plugins running with JavaFX. I often stumble across the problem that the FXClassloader is not loading a random JavaFX class, hence my application is not starting correctly:
Here are some logs:

```
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'org.apache.felix.shell.Command' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@46d086cc[org.apache.felix.scr:2.0.14.v20180822-1822(id=172)]
FXClassLoader#getModuleLayer - Use directory 'C:\appl\Java\javafx-sdk-11.0.2\lib'
FXClassLoader#getModuleLayer - Inspecting path 'C:\appl\Java\javafx-sdk-11.0.2\lib'
FXClassLoader#getSWTClassloader - Fetching SWT-Classloader
FXClassLoader#getSWTClassloader - Done SWT-Classloader
FXClassLoader#getModuleLayer - Parent Classloader: org.eclipse.equinox.launcher.Main$StartupClassLoader@4e7dc304
FXClassLoader#advancedModuleLayerBoostrap - Using advanced layer creation to apply patches
FXClassLoader#advancedModuleLayerBoostrap - javafx.swt => C:\appl\Java\javafx-sdk-11.0.2\lib\javafx-swt.jar
FXClassLoader#advancedModuleLayerBoostrap - javafx.base => C:\appl\Java\javafx-sdk-11.0.2\lib\javafx.base.jar
FXClassLoader#advancedModuleLayerBoostrap - javafx.controls => C:\appl\Java\javafx-sdk-11.0.2\lib\javafx.controls.jar
FXClassLoader#advancedModuleLayerBoostrap - javafx.fxml => C:\appl\Java\javafx-sdk-11.0.2\lib\javafx.fxml.jar
FXClassLoader#advancedModuleLayerBoostrap - javafx.graphics => C:\appl\Java\javafx-sdk-11.0.2\lib\javafx.graphics.jar
FXClassLoader#advancedModuleLayerBoostrap - javafx.media => C:\appl\Java\javafx-sdk-11.0.2\lib\javafx.media.jar
FXClassLoader#advancedModuleLayerBoostrap - javafx.swing => C:\appl\Java\javafx-sdk-11.0.2\lib\javafx.swing.jar
FXClassLoader#advancedModuleLayerBoostrap - javafx.web => C:\appl\Java\javafx-sdk-11.0.2\lib\javafx.web.jar
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.graphics/com.sun.javafx.application=BUNDLE(@250)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.graphics/com.sun.javafx.scene=BUNDLE(com.jfoenix@9.0.10)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.controls/com.sun.javafx.scene.control.behavior=BUNDLE(@61)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.base/com.sun.javafx.event=BUNDLE(@67)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.graphics/com.sun.javafx.tk=BUNDLE(@18)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.graphics/com.sun.glass.ui=BUNDLE(@250)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.graphics/com.sun.javafx.tk=BUNDLE(@19)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.controls/com.sun.javafx.scene.control.behavior=BUNDLE(com.jfoenix@9.0.10)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.base/com.sun.javafx.event=BUNDLE(org.controlsfx@11.0.1)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.base/com.sun.javafx.event=BUNDLE(@19)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.controls/com.sun.javafx.scene.control.behavior=BUNDLE(org.controlsfx@11.0.1)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.controls/com.sun.javafx.scene.control=BUNDLE(com.jfoenix@9.0.10)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.graphics/com.sun.javafx.scene=BUNDLE(@19)'
JavaModuleLayerModification#applyConfigurations - Exporting 'javafx.graphics/com.sun.javafx.tk=BUNDLE(@61)'
FXClassLoader#getModuleLayer - Module created: org.eclipse.fx.osgi.fxloader.jpms.ModuleLayerWrapper@7f3cccf0
FXClassLoader#getSWTClassloader - Fetching SWT-Classloader
FXClassLoader#getSWTClassloader - Done SWT-Classloader
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - null - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.image.Image' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.image.Image - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.stage.Stage' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.stage.Stage - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.Parent' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.Parent - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.layout.StackPane' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.layout.StackPane - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.stage.StageStyle' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.stage.StageStyle - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.collections.ObservableList' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - interface javafx.collections.ObservableList - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.beans.value.ObservableValue' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - interface javafx.beans.value.ObservableValue - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.concurrent.Task' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.concurrent.Task - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.layout.Pane' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.layout.Pane - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.Node' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.Node - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.layout.GridPane' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.layout.GridPane - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.event.Event' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.event.Event - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.event.ActionEvent' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.event.ActionEvent - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.concurrent.WorkerStateEvent' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.concurrent.WorkerStateEvent - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.event.EventHandler' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - interface javafx.event.EventHandler - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.beans.Observable' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - interface javafx.beans.Observable - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.stage.WindowEvent' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.stage.WindowEvent - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.control.Label' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.control.Label - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.control.ComboBox' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.control.ComboBox - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.control.TextField' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.control.TextField - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.control.PasswordField' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.control.PasswordField - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.control.Button' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.control.Button - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.animation.FadeTransition' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.animation.FadeTransition - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.fxml.FXML' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - interface javafx.fxml.FXML - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.control.ButtonType' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.control.ButtonType - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.beans.property.BooleanProperty' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.beans.property.BooleanProperty - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.scene.control.SingleSelectionModel' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.scene.control.SingleSelectionModel - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.beans.value.ChangeListener' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - interface javafx.beans.value.ChangeListener - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.beans.property.ReadOnlyObjectProperty' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.beans.property.ReadOnlyObjectProperty - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.beans.InvalidationListener' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - interface javafx.beans.InvalidationListener - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.beans.property.StringProperty' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.beans.property.StringProperty - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.util.Duration' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
FXClassLoader#findClassJavaFX11 - class javafx.util.Duration - ended
FXClassLoader#findClassJavaFX11 - started
FXClassLoader#findClassJavaFX11 - Loading class 'javafx.beans.property.DoubleProperty' for org.eclipse.osgi.internal.loader.EquinoxClassLoader@169465a1[AppRCP:4.0.0.qualifier(id=129)]
FXClassLoader#findClassJavaFX11 - Using classloader org.eclipse.fx.osgi.fxloader.FXClassLoader$1@6ad8c63d
!SESSION 2020-07-02 21:10:52.817 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.7
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product AppAppl.product -clearPersistedState
Command-line arguments:  -product AppAppl.product -data C:\workspaces\workspace/../runtime AppBranding.product -dev file:C:/workspaces/workspace/.metadata/.plugins/org.eclipse.pde.core/AppBranding.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -clearPersistedState

!ENTRY org.eclipse.equinox.app 4 0 2020-07-02 21:11:02.839
!MESSAGE Exception in Application start method
!STACK 0
java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: javafx/stage/Screen
	at com.myapp.AppLifeCycle.processAdditions(AppLifeCycle.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:248)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:139)
	at org.eclipse.fx.ui.workbench.base.AbstractE4Application.createE4Workbench(AbstractE4Application.java:330)
	at org.eclipse.fx.ui.workbench.fx.E4Application.initE4Workbench(E4Application.java:383)
	at org.eclipse.fx.ui.workbench.fx.E4Application$1.run(E4Application.java:232)
	at org.eclipse.fx.ui.workbench.fx.E4Application.jfxStart(E4Application.java:271)
	at org.eclipse.fx.ui.workbench.fx.DefaultJFXApp.start(DefaultJFXApp.java:60)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 1 more
Caused by: java.lang.ClassNotFoundException: javafx.stage.Screen cannot be found by AppRCP_4.0.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 23 more

```
As you can see it could find JavaFX classes for that bundle. It just randomly happen anywhere in the code. Any ideas?

**Comment by tomsontom** [comment]
The classloading hook we use is: ClassLoaderHook#postFindClass where the JavaDoc says:

```
/**
	 * Called by a {@link BundleLoader#findClass(String)} method after delegating to the resolved constraints and 
	 * local bundle for a class load.  This method will only be called if no class was found
	 * from the normal delegation.
	 * @param name the name of the class to find
	 * @param classLoader the bundle class loader
	 * @return the class found by this hook or null if normal delegation should continue
	 * @throws ClassNotFoundException to terminate the delegation and throw an exception
	 */
	public Class<?> postFindClass(String name, ModuleClassLoader classLoader) throws ClassNotFoundException {
```

and I don't see how we won't log the lookup but to be extra sure you might want to add a conditional break point in FXClassLoader#postFindClass at Line 110 and print a System.err if you don't see Equinox calling that method for javafx.stage.Screen you know that this is a bug in Equinox.

**Comment by tomsontom** [comment]
another thing that might be interesting is that you put a conditional break point to `BundleLoader#findClassInternal` and when you look up the Screen-class you could see why it is not consulting the hooks.

**Comment by qtran** [comment]
It's difficult to put a conditional break point since it happens randomly with any JavaFX class but I'll try to debug the BundleLoader somehow

**Comment by tomsontom** [comment]
Well I would just insert a debug statement who syserrs the call. Just „return false“ from the condition which allows to inject random code

**Comment by qtran** [comment]
I don't know how this happened, but I filtered out the most important log above. At least I've found now the error case. Each time a JavaFX class is not found we run into a the loop detection in line 112. Is this a multi threading issue? Since we do a lot of stuff in multiple threads during the startup.

**Comment by tomsontom** [comment]
Line 112 from which class?

**Comment by qtran** [comment]
FXClassloader. I just made simple test by making `FXClassLoader#postFindClass` `synchronized` and it fixed the issue but I don't know the impact in performance since I'm not savvy on OSGI.

**Comment by tomsontom** [comment]
Great - I think adding synchronize is not a problem but I’ll double check that.
